#include <gtest/gtest.h>
#include "analysis/Tree.hpp"

class TreeTest : public ::testing::Test {
protected:
    void SetUp() override {

    }

    Tree randomTree{25};
};

// Make sure that every node except for the root has only two children
TEST_F(TreeTest, RandomTreeBifurcating) {
    bool bifurcating = true;
    auto postOrder = randomTree.getPostOrder();
    for(auto node : postOrder){
        if(! node->isRoot && ! node->isTip){
            if(node->descendants.size() != 2){
                bifurcating = false;
                break;
            }
        }
    }

    EXPECT_EQ(bifurcating, true);
}

// Make sure we have initialized the right number of tips
TEST_F(TreeTest, RandomTreeTipCount) {
    int size = randomTree.getTips().size();
    std::cout << size << std::endl;
    EXPECT_EQ(size, 25);
}

// The newick strings from a tree generated by one of our newicks should be identical
TEST_F(TreeTest, NewickReplication) {
    std::string newick = randomTree.generateNewick();
    Tree newickTree(newick);
    std::string regeneratedNewick = newickTree.generateNewick();
    EXPECT_EQ(newick, regeneratedNewick);
}